### ISSUE TITLE
Enqs 0.2.x - Queue Functions

### ISSUE THREAD

**Issue by fnhusky** [fnhusky/enqs#3]
Queue functions for enqs package

## Tasks

- [ ] Add Job
- [ ] Get Job
   - [ ] By Key
   - [ ] All Jobs By Job Name
- [ ] Delete Job
   - [ ] By Key
   - [ ] All Jobs By Job Name
- [ ] Retry Job
   - [ ] By Key
   - [ ] All Jobs By Job Name
